Content interface for MicroOVN
canonical/lxd-pkg-snap pull request #151
Opened 2023-09-18 14:40 UTC by masnax

Adds support for the hypothetical `MicroOVN` `ovn-conf` slot, which does not yet exist. This will be a draft until it does.

2023-09-18 14:42 UTC, masnax commented on snapcraft/hooks/disconnect-plug-ovn-run
> +        mkdir -p "${OVS_SYSCONFDIR}/openvswitch"
Not sure if there should be some cleanup here in case we set up `openvswitch_builtin`in `daemon.start`, then installed and uninstalled MicroOVN.

2023-10-20 03:37 UTC, simondeziel requested changes

2023-10-20 03:37 UTC, simondeziel commented on snapcraft/hooks/connect-plug-ovn-data
> +fi
`<code-golf>`
`[ -d /etc/ovn ] || mkdir /etc/ovn`
`</code-golf>`

2023-10-20 03:37 UTC, simondeziel commented on snapcraft/hooks/connect-plug-ovn-data
> +ln -snf ${SNAP_DATA}/microovn/data/pki/cacert.pem /etc/ovn/ovn-central.crt
`shellcheck` wants those to be quoted.

2023-10-20 03:37 UTC, simondeziel commented on snapcraft/hooks/connect-plug-ovn-run
> +ln -snf ${SNAP_DATA}/microovn/run/switch /run/openvswitch
Missing quotes as well.

2023-10-20 03:37 UTC, simondeziel commented on snapcraft/hooks/disconnect-plug-ovn-run
> +        set -e
I'm probably missing something but I couldn't find an explanation for having `OVS_RUNDIR` set outside that subshell? In fact, I don't understand the purpose of those 2 subshells. If you could shed some light I'd appreciate, thanks.

2023-11-16 03:46 UTC, tomponline commented
@masnax are you still working on this? If not please could you close until you get back to it. Ta

2023-11-29 23:25 UTC, closed without merging